backend:
  name: git-gateway
  branch: main
  
display_url: https://friendly-brahmagupta-13f958.netlify.app
site_url: https://friendly-brahmagupta-13f958.netlify.app

media_folder: 'static' # Folder where user uploaded files should go
public_folder: 'static'

collections:
   - name: "about"
     label: "about page"
     folder: "content"
     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
     fields:
         - {label: "Title", name: "title", widget: "string"}
         - {label: "Body", name: "body", widget: "markdown"}
     
  - name: "post"
    label: "post"
    label_singular: "post"
    folder: "content/post"
    create: true
    # adding a nested object will show the collection folder structure
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field     
    fields:
         - {label: "Title", name: "title", widget: "string"}
         - {label: "Body", name: "body", widget: "markdown"}         
