backend:
  name: git-gateway
  branch: main
  
display_url: https://friendly-brahmagupta-13f958.netlify.app
site_url: https://friendly-brahmagupta-13f958.netlify.app

media_folder: 'static' # Folder where user uploaded files should go
public_folder: 'static'

collections:
   - name: "pages"
     label: "Pages"
     files:
     - file: "content/about.md"
       label: "About"
       name: "about"
       fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
     - file: "config.yaml"
       label: "Config"
       name: "config"
       fields:
          - {label: "baseurl", name: "baseurl", widget: "string"}


   - name: post
     label: Post
     label_singular: 'Post'
     folder: content/post
     create: true
     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
     # adding a nested object will show the collection folder structure
     nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
     fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime 
      - label: Body
        name: body
        widget: markdown
     # adding a meta object with a path property allows editing the path of entries
     # moving an existing entry will move the entire sub tree of the entry to the new location
     meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
