backend:
  name: git-gateway

media_folder: 'static' # Folder where user uploaded files should go
public_folder: 'static'

collections:
     - name: "About"
       label: "About"
       folder: "content"
       create: true
       slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
       fields:
         - { label: "Title", name: "title", widget: "string" }
         - { label: "Date", name: "date", widget: "date" }
         - { label: "Tags", name: "tags", widget: "list" }
         - { label: "Categories", name: "categories", widget: "string" }
         - { label: "Body", name: "body", widget: "markdown" }
         - { label: "Description", name: "description", widget: "string"}
