backend:
  name: git-gateway
  branch: main

media_folder: 'static' # Folder where user uploaded files should go
public_folder: 'static'

collections:
   - name: "about"
     label: "about page"
     folder: "content"
     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
     fields:
         - {label: "Title", name: "title", widget: "string"}
         - {label: "Body", name: "body", widget: "markdown"}
         
   - name: "post"
     label: "post"
     folder: "content/post/"
     slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
     fields:
         - {label: "Title", name: "title", widget: "string"}
         - {label: "Body", name: "body", widget: "markdown"}         
